# The Agent's Epistemic Baggage: Self-Reinforcing Epistemic Drift in Agent Memory

*A risk model for how agent-generated inferences change epistemic status and operational authority through the memory lifecycle, and how to make those transitions explicit audit objects.*

## What this can be used for

Anyone who builds, procures, or audits agentic AI systems needs to be able to answer one question: how does the system know the difference between what it has observed and what it has assumed? More precisely: how does it represent and preserve the distinction between received information and agent-generated inference? This text describes a risk mechanism, here called self-reinforcing epistemic drift, that can arise when that distinction is lost. The model applies specifically to agentic AI systems with writable persistent memory, where agent-generated representations can be stored, retrieved, and influence later inferences or actions. The description is intended as input in three situations: risk analysis in the design of memory architectures, audit questions in the review of agentic systems, and an argument for why memory management is a governance question and not merely a technical implementation detail.

The model is presented as a conceptual risk model with an audit orientation. Its drift mechanisms, memory schema, and lifecycle test protocol form the proposed conceptual core; the formalization of full control requirements, metrics, and acceptance criteria is identified as open work.

## Scope

Self-evolving agents can change along several pathways: model, memory, tool, and workflow (Shao et al., 2026). This text addresses the memory pathway. The tool and workflow pathways have their own risk profiles and are left outside the scope.

## Two layers of baggage

The agent's epistemic baggage consists of two layers with different rates of change and different governance needs. The relatively stable layer comprises model weights, system instructions, and tool policies, and is more directly addressed by established model, testing, and configuration controls. The mutable layer comprises episodic memories, summaries, conclusions, and stored experiences, and requires write gates, provenance, validation, and deletion routines. As a working hypothesis rather than an established finding, the mutable memory layer is less explicitly operationalized in current governance guidance, and it is this layer that the mechanisms below describe.

## The drift mechanisms

The agent starts with epistemic baggage: patterns from training data, instructions, prior experiences, stored memories, and conclusions. When new information arrives, it is processed together with this baggage, an interpretation is formed, and something is stored. What is stored varies across architectures, from raw data to summaries and conclusions.

Drift arises through two distinct minimal mechanisms. They can co-occur and reinforce each other, but neither requires the other.

**Mechanism 1: the re-storage loop.** For recursive propagation through the write and retrieval cycle to be possible, four structural conditions must hold. They are necessary but not sufficient for drift: the loop must also contain inaccurate, unsupported, misclassified, or epistemically degraded material.

1. Agent-generated material is stored.
2. That material can be retrieved in later tasks.
3. The retrieved material can influence inference or action, whether permitted or not.
4. The resulting material can be written back to memory.

Each condition is also a control point: the chain breaks wherever one of them is interrupted.

Similarity-based retrieval is not a necessary condition for this loop, but it is a common amplifier. Many memory systems use semantic similarity as a central signal, often in combination with recency, importance, metadata, or policy rules. When the same representational patterns influence what is written, what is retrieved, and how the retrieved material is weighted, a confirming loop can arise without anyone having designed it. Two components of this amplification pathway are empirically documented: experience-following and error propagation (Xiong et al., 2026). LLM agents exhibit an experience-following property, where high similarity between the current task and a retrieved memory record yields strongly similar outputs, and errors in stored experiences can be retrieved, imitated, and stored again, a mechanism documented as error propagation. But an erroneous record retrieved through recency, rules, or metadata can also propagate.

**Mechanism 2: consolidation drift.** The second mechanism does not require the retrieval loop at all:

1. Material is stored.
2. It is transformed through summarization or compression.
3. Provenance, validation status, temporal validity, or evidential support is lost in the transformation.
4. The transformed representation replaces the original or receives greater retrieval or decision priority.

Architectures that periodically consolidate memory introduce an additional transformation point: each consolidation is a new interpretive event in which status information can be lost even if it was preserved at the initial write. Knowledge degradation through iterative summarization has been identified as a distinct risk in its own right (Lam et al., 2026). Note the two-phase structure: the corruption occurs at consolidation, before any retrieval takes place, but it acquires action consequences only when the altered memory is later used. The two phases have different control points: consolidation gates for the corruption phase, authority policy for the activation phase.

## What must not be collapsed: a memory schema

A central auditability failure occurs when stored records collapse distinctions that must be kept in separate fields. A single "status label" is not enough, because several different dimensions are involved: what kind of thing the record is, where it came from, how well supported it is, how current it still is, and how it has actually been used. The fields below split into two related kinds: those that describe a record's epistemic status, whether a claim is supported and how current it is, and those that describe its operative use, whether it was permitted to influence a decision or action and what it actually did. Both kinds sit in a single schema because it is the joint trace across both, not either kind alone, that makes drift auditable. The schema is a logical audit schema, not a requirement that every field applies to every record type or that all records coexist in a single physical table: field applicability is conditional on representation type, and operational events can be linked to the epistemic records they consume. An auditable memory schema needs at minimum:

| Field | Examples |
|---|---|
| Representation type | received input, sensor event, tool output, external source claim, agent inference, decision, action |
| Provenance | source, timestamp, tool, agent, link to underlying evidence |
| Validation status | untested, supported, contradicted, validated, rejected |
| Temporal validity | current, stale, expired, superseded |
| Evidence relation | which records or sources support or contradict this record, including the strength, independence, and quality of that support |
| Change history | created, summarized, reclassified, superseded |
| Epistemic transition basis | new evidence, corroboration, contradiction resolution, validated outcome |
| Authority basis | policy rule, risk classification, human approval, delegated permission |
| Usage and decision lineage | retrieval event, rank, retrieval score, prompt position, explicit reference in reasoning or output, consuming agent, affected decision or action |

Several clarifications. First, representation type also covers stored records of the agent's own outputs: a record representing a decision or an action is part of the audit schema on the same basis as an externally sourced claim, and carries its own provenance and change history. It does not, however, carry a meaningful truth-based validation status in the same sense a claim does: an action is not supported or contradicted, it is authorized, executed, successful, or failed, and its weight is assessed through the evidence it was based on, together with its usage and decision lineage. Second, provenance shows where the information came from, not that it is correct; inputs and external sources can also be wrong, but without provenance the question of correctness cannot even be asked after the fact. Third, uncertainty should be grounded in the evidence and validation state, rather than relying solely on the model's self-reported confidence, which measures something else; this is also why evidence relation carries the strength, independence, and quality of the supporting or contradicting material, rather than treating support as a binary property. Fourth, validation status and temporal validity are kept separate because they track different things: a record can remain validated while becoming stale, so validation status marks whether a claim held up when it was tested, and temporal validity marks whether it is still current now. Superseded appears in both change history and temporal validity for the same reason rather than by duplication: change history logs the event that a record was superseded, while temporal validity reports the record's present state as a consequence of that event; one is a log entry, the other is a status. Fifth, epistemic transition basis and authority basis are kept separate because they answer different questions: epistemic transition basis is why a claim became more likely to be true, such as new evidence or a resolved contradiction; authority basis is why a record was allowed to influence a decision, such as a policy rule or a human approval. A policy decision does not make a claim truer, and new evidence does not by itself grant permission to act; collapsing the two into one field would let an authority increase read as if it were also an epistemic one. Sixth, the lineage field makes exposure and recorded use observable, not causal influence: it can show that a record was retrieved, placed in context, and available when a decision was made, but not that the record caused the decision. The distinction between exposure, use, and causal influence is developed further below, together with the testing it requires.

When memory is later retrieved, a previous interpretation can be used as a premise for the next decision. If these fields have been lost or were never kept apart, the agent can treat an unconfirmed inference as if it were validated knowledge.

## Two initiating sources, shared amplification mechanisms

The drift can be initiated endogenously, when the agent itself generates the erroneous inference, or exogenously, when misleading material enters memory from outside through adversarial memory injection, faulty tool outputs, or biased feedback (Xie et al., 2026). Both sources feed the same amplification pathways described above, and the boundary is not clean: endogenous errors can produce safety consequences, and exogenous contamination can be unintentional rather than adversarial. The practical reason to keep the distinction is that the two sources call for partly different controls. Both pathways require lifecycle integrity and auditable state transitions: write permissions, traceability, version control, permitted status and authority transitions, and protection against unauthorized overwriting. The exogenous pathway additionally requires controls specifically addressing externally initiated contamination, including source authentication, trust-boundary enforcement, input isolation, and adversarial memory-injection testing. Note that permitted status transitions tie integrity to the schema above: a transition from untested to validated without a supporting evidence relation is then not merely a drift risk but an integrity violation, which makes it mechanically detectable where the transition rule, the recorded epistemic transition basis, and supporting lineage requirements are encoded and enforced. The same logic applies on the authority side: a transition that grants a record more permitted authority without a supporting authority basis is a distinct integrity violation, detectable wherever the authority-transition rule and the recorded authority basis are encoded and enforced. A risk analysis should cover both sources.

## The core problem

An inference held in memory can undergo two different transitions. Epistemic state transition describes movement between validation states, such as untested, supported, contradicted, validated, or rejected. Epistemic promotion is the subset of transitions that assigns a stronger validation status; movement toward contradicted or rejected is a transition but not a promotion. Operational activation moves a record along a separate axis describing use: from stored, to retrievable, to exposed in context, to used, to action-influencing. The two axes are related but not identical, and a record can move along one without moving along the other. Epistemic promotion is justified only when it rests on sufficient, traceable evidential support; whether the evidence itself was collected in a policy-permitted way is a separate compliance question, since improperly obtained evidence can still be true and permitted evidence can still be wrong.

An epistemic drift event occurs when a record gains or retains a validation status that overstates its evidential support; loses material provenance, qualification, or contradictory context while retaining that status; or fails to be revised when contradicted by sufficient evidence. Operational authority does not itself constitute epistemic drift; it determines the reach and consequences of drift. Unauthorized authority escalation is a separate control failure: a record can be granted more influence than policy allows regardless of whether its epistemic status is sound. The combined risk arises whenever a record affected by epistemic drift influences a decision or action, whether that influence was policy-permitted or unauthorized; a drifted record does not need to also escalate its authority to reach a decision, since a policy that grants influence to whatever the system currently labels valid will act on a drifted label as readily as a sound one. Self-reinforcing epistemic drift is the cumulative condition that results when epistemic drift events recur or go uncorrected, causing the system's operational knowledge state to become progressively less anchored to its evidence, driven by the system's own memory lifecycle. The damage is primarily epistemic, but the evidence indicates it can go further. Memory accumulation has been associated with safety-alignment degradation in self-evolving agents (Shao et al., 2026), and contaminated or biased memory updates have produced substantial safety degradation in long-horizon memory benchmarks (Xie et al., 2026).

Central to the model is the concept of operational authority, which is not a single scalar degree but a profile of four related, distinct variables: permitted authority, observed exposure, recorded use, and causal influence. Together these form a record's operational influence profile, and none of the four reduces to the others: permitted authority can be conferred through instruction priority, tool permissions, mandatory-use rules, and downstream decision policies, while observed exposure is shaped by separate mechanisms such as retrieval ranking, retrieval frequency, and position in context; neither, by itself, establishes recorded use or causal influence.

Permitted authority is how policy specifies a record is allowed to influence the system. Observed exposure is whether the record was retrieved and placed in context, available when a decision was made; retrieval rank, score, and prompt position make this observable. Recorded use is whether the record was explicitly referenced, copied, or cited in the system's reasoning or output; usage and decision lineage make this observable. Causal influence is whether the decision would have differed had the record been absent or replaced; neither exposure nor recorded use establishes this on its own, it requires controlled testing, such as replaying the same decision with and without the memory record and comparing the resulting inference, tool choice, and action. An audit finding arises where observed exposure, recorded use, or demonstrated influence exceeds a record's permitted authority. A separate assurance finding arises where causal influence is claimed or relied upon but cannot be supported by controlled replay or other adequate evidence. Mere exposure does not establish recorded use or causal influence. However, exposure is itself an audit finding where access or authority policy prohibited the record from being placed in that context. A system that treats exposure as proof of causation would be making, at the level of the audit itself, the same kind of unearned status increase this model warns against at the level of the agent's memory: decision lineage shows that a memory was available and used, it does not by itself prove how much the memory caused the decision.

## Positioning relative to related work

Several strands of work address adjacent phenomena. Error propagation (Xiong et al., 2026) names the empirical mechanism in the retrieval loop: errors that are retrieved, imitated, and re-stored. Memory misevolution (Shao et al., 2026; Xie et al., 2026) names the broader phenomenon: gradual behavioral drift through memory evolution, including alignment effects. On the governance side, the SSGM framework (Lam et al., 2026) proposes an architecture that decouples memory evolution from execution through write validation, constrained retrieval, and periodic reconciliation against an immutable log, together with testable hypotheses and evaluation protocols for whether governance gates can bound aggregate semantic drift, assessed against a ground truth reference.

Self-reinforcing epistemic drift, as described here, operates at a different level. SSGM asks how far the memory has drifted from an anchored state and whether architectural gates can bound that drift. This model asks how a specific claim changed epistemic status, how it was subsequently operationally activated, and whether the relationship between those transitions can be reconstructed. The two are complementary: in principle, an aggregate semantic-drift measure may remain low while an individual unvalidated record acquires substantial decision authority, which is precisely the record-level case the audit objects here are designed to catch. The model's contribution is to make the record-level transition in epistemic status an explicit audit object: how a particular inference changes classification, validation state, and operational authority over time, with a schema of separable fields and a testable lifecycle protocol.

A second complementarity concerns provenance. SSGM uses cryptographic provenance to ensure a memory unit was generated by a trusted source. That authenticates origin. The schema here additionally separates origin from correctness: validation status and evidence relation are distinct fields, because a trusted source can be wrong, and an authenticated agent inference is still an inference.

This positioning yields the model's central research questions. First: can an agent-generated inference acquire or retain a higher epistemic status without sufficient traceable evidential support? Second: can a memory record be granted greater permitted authority without a recorded, authorized, and risk-appropriate policy basis, or be exposed, used, or causally influential beyond the scope of that authority? Third, and this is the model's specific audit contribution: can either transition, and the relationship between them, be reconstructed across the memory lifecycle? An epistemic promotion without a corresponding recorded and adequate evidential basis, or a status that persists despite sufficient contradicting evidence, is a testable indicator of epistemic drift; an authority increase without a recorded and adequate policy basis is a testable indicator of unauthorized escalation. Neither absence is conclusive proof, because relevant evidence or authorization may exist outside the captured lineage, or the logging itself may be incomplete. But wherever policy requires that basis to be recorded, its absence is itself a control failure, regardless of whether the underlying claim happens to be true.

Functionally the drift resembles confirmation bias, but it is an agent-specific implementation of a broader self-reinforcing epistemic dynamic, not the same mechanism. In agentic systems the risk can be amplified by programmable persistence, high repetition rate, consistent reuse, and possible propagation across tasks or instances. At the same time, potential corrective mechanisms, such as forgetting, environmental feedback, and external review, may be absent unless explicitly built in.

## From breaking point to control

The drift is not inevitable, but where the controls are placed determines whether they work. In the MemEvoBench experiments, static prompt-based defenses were insufficient against the tested forms of memory misevolution (Xie et al., 2026). Instructing the agent to critically evaluate sources is not, on that evidence, a sufficient control against memory-driven drift. Controls cannot rely on prompting alone: enforceable controls are needed within the memory lifecycle and, for consequential uses, at the decision or action boundary. On the mitigation side, selective memory addition combined with selective deletion has been shown to reduce error propagation and improve task performance (Xiong et al., 2026).

A boundary on the evidence should be stated plainly: the cited studies provide empirical support for experience-following and error propagation (Xiong et al., 2026); safety-alignment degradation after memory accumulation in the tested self-evolving agents (Shao et al., 2026); and safety degradation under contaminated or biased memory updates in MemEvoBench (Xie et al., 2026). Iterative summarization has also been identified as a mechanism of semantic drift, though on conceptual and formal grounds rather than through empirical validation of the status transition described here. The specific epistemic status-transition model, the operational influence profile, and the audit controls derived from them remain to be empirically tested.

The breaking points can be formulated as controls: retain or securely reference the underlying evidence for a risk-appropriate period, subject to privacy, data-minimization, retention, and access-control requirements; keep the schema fields above separate and populated; validate before consolidation; and perform risk-based reconciliation against authoritative or independent evidence, particularly after conflicts, consolidation, or before high-impact actions. A complete control additionally needs to specify what is controlled, which requirement applies, what evidence the audit requires, how the control is tested, what outcome is acceptable, and who is accountable.

A lifecycle test protocol should cover at least five cases, since a single labeled error mainly tests whether the system respects an explicit label:

1. A labeled, untested, and incorrect inference.
2. A plausible but incorrect inference with incomplete provenance.
3. An inference that is stored and later contradicted by new, independent evidence.
4. Repeat cases 1 through 3 after one or more consolidation cycles, to test whether provenance, validation state, and evidential support survive transformation.
5. New, sufficiently validated evidence that legitimately contradicts an older stored record and should result in a justified update.

For cases 1 through 4, trace whether the record is retrieved, appears in context for a decision, is copied, changes validation status, gains permitted authority, or is corrected. Case 3 tests the hardest requirement on the blocking side: that the system can downgrade status, not merely preserve it. Case 5 tests the opposite failure direction: a system can pass the first four cases by never trusting new memories, which produces knowledge ossification rather than safety, a variant of the stability-plasticity conflict that SSGM identifies as a fundamental trade-off (Lam et al., 2026). For case 5, measure whether the system accepts the justified change, preserves both versions and the conflict history, downgrades the outdated record, and avoids rejecting everything that contradicts established memory. Together the five cases make the protocol bidirectional: both improper promotion and improper blocking are tested. For the exogenous variant, the corresponding test is a controlled memory injection from outside.

Where a record is associated with a decision or action, repeat the decision under controlled conditions with the record included, removed, and where appropriate replaced by a neutral or contradictory record. Hold the model and prompt version, the remaining memory state, and tool outputs constant across runs; use a controlled seed where available; match context position and approximate token length; and run repeated paired trials when deterministic replay is not possible, since a single differing run does not by itself distinguish the record's effect from sampling variance. Compare the resulting inference, tool selection, parameters, and action. Lineage can establish exposure, temporal association, and recorded use; controlled intervention provides stronger evidence of causal influence.

Beyond this lies a question that storage hygiene does not solve: the authority of memory. Even with complete provenance, the system must decide how much weight a retrieved memory should carry relative to a fresh observation. That is a policy question about decision rules, not a technical question about storage, and it belongs in the same reasoning as consequence gates for agentic decisions: conclusions whose consequences are high-impact, irreversible, externally consequential, or otherwise risk-classified should pass a checkpoint before they are allowed to govern.

## Summary of the audit objects

The model proposes four things an auditor should be able to observe in an agentic memory system:

1. Record classification and evidential state: the schema fields for representation type, provenance, validation status, temporal validity, and evidence relation exist, are separated, and are populated.
2. Epistemic status change history: transitions in validation status are recorded, traceable, and linked to a sufficient and traceable evidential basis.
3. Authority change history: transitions in permitted authority are recorded, traceable, and linked to a recorded, authorized, and risk-appropriate policy basis, kept separate from the evidential basis for epistemic transitions.
4. Operational authority in use: permitted authority is defined in policy, observed exposure and recorded use are each traceable through lineage, and causal influence can be evaluated through controlled replay, for any record reaching a decision or action regardless of whether its epistemic status was sound and regardless of whether its use was policy-permitted or unauthorized.

Epistemic drift becomes auditable when changes in a record's validation status and evidential support can be traced across the memory lifecycle, and when any accompanying change in operational authority is traced as a separate, related object rather than folded into the same status. Where that joint traceability exists, both the epistemic chain (agent-generated inference → persistent representation → epistemic promotion → apparently validated knowledge) and any operational activation that followed it can be reconstructed and tested, creating a basis for corrective intervention. Where it does not, drift or unwarranted authority may remain undetected until they affect outcomes.

## References

Xiong, Z., Lin, Y., Xie, W., He, P., Liu, Z., Tang, J., Lakkaraju, H., & Xiang, Z. (2026). How Memory Management Impacts LLM Agents: An Empirical Study of Experience-Following Behavior. Proceedings of the 64th Annual Meeting of the Association for Computational Linguistics (ACL 2026), pp. 623-645. DOI: [10.18653/v1/2026.acl-long.27](https://doi.org/10.18653/v1/2026.acl-long.27). arXiv:[2505.16067](https://arxiv.org/abs/2505.16067).

Shao, S., Ren, Q., Qian, C., Wei, B., Guo, D., Yang, J., Song, X., Zhang, L., Zhang, W., Liu, D., & Shao, J. (2026). Your Agent May Misevolve: Emergent Risks in Self-evolving LLM Agents. International Conference on Learning Representations (ICLR 2026). arXiv:[2509.26354](https://arxiv.org/abs/2509.26354).

Xie, W., Guo, S., Zhang, F., Xia, T., Yang, X., Ma, L., Yan, J., & Ren, Q. (2026). MemEvoBench: Benchmarking Safety Risks from Memory Misevolution in LLM Agents. arXiv:[2604.15774](https://arxiv.org/abs/2604.15774).

Lam, C., Li, J., Zhang, L., & Zhao, K. (2026). Governing Evolving Memory in LLM Agents: Risks, Mechanisms, and the Stability and Safety Governed Memory (SSGM) Framework. arXiv:[2603.11768](https://arxiv.org/abs/2603.11768).
